### ISSUE TITLE
GKE and Trend admission-controller

### ISSUE THREAD

**Issue by sylvain-actual** [trendmicro/cloudone-container-security-helm#9]
Hello,

I have this warning on all my GKE 

This cluster has an admission webhook installed that is intercepting system critical requests in the last 24 hours. Intercepting these requests can impact availability of the GKE Control Plane.

Intercepting resources in the kube-system namespace

If I check the ValidatingWebhookConfiguration, I can see : 

```
namespaceSelector:
    matchExpressions:
    - key: ignoreAdmissionControl
      operator: DoesNotExist
```

It looks kube-system namespace is not ignored by default.

How can I ignored it from ValidatingWebhook ?

Should I change this rule ?

Thx

**Comment by sylvain-actual** [comment]
If I try to set in values (deploy with argocd)

```
              admissionController:
                validationNamespaceSelector:
                  matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: NotIn
                    values:
                    - kube-system
```

I have this message :

```
one or more objects failed to apply, reason: ValidatingWebhookConfiguration in version "v1" cannot be handled as a ValidatingWebhookConfiguration: json: cannot
unmarshal string into Go struct field LabelSelectorRequirement.webhooks.namespaceSelector.matchExpressions.values of type []string. Retrying attempt #4 at 3:27PM.
```

But I am able to edit the ValidatingWebhookConfiguration in GKE and set the expression.

**Comment by zayaanmoez** [comment]
Hi @sylvain-actual,

If you provide namespace exclusions in helm overrides, the admission controller and other components should exclude those namespaces. By default the exclusion list has kube-system in it. Did you try setting kube-system in helm overrides:
```
cloudOne:
  exclusion: 
    namespaces: [kube-system]
```

https://github.com/trendmicro/cloudone-container-security-helm/blob/master/values.yaml#L39

**Comment by sylvain-actual** [comment]
Hello,

This is the manifest generated and applied

```
cloudOne:
  admissionController:
    enabled: false
  apiKey: XXXXX
  endpoint: XXXXX
  exclusion:
    namespaces:
      - kube-system
  inventoryCollection:
    enabled: true
  runtimeSecurity:
    enabled: true
  vulnerabilityScanning:
    enabled: true
```


I have desactivated admissionController (set to false)
